export const ADD_ORDER_INIT = "ADD_ORDER_INIT";
export const ADD_ORDER_SUCCESS = "ADD_ORDER_SUCCESS";
export const ADD_ORDER_FAIL = "ADD_ORDER_FAIL";
export const ADD_ORDER_RESET = "ADD_ORDER_RESET";

export const GET_ORDER_INIT = "GET_ORDER_INIT ";
export const GET_ORDER_SUCCESS = "GET_ORDER_SUCCESS ";
export const GET_ORDER_FAIL = "GET_ORDER_FAIL ";
export const GET_ORDER_RESET = "GET_ORDER_RESET ";

export const GET_SINGLE_ORDER_INIT = "GET_SINGLE_ORDER_INIT ";
export const GET_SINGLE_ORDER_SUCCESS = "GET_SINGLE_ORDER_SUCCESS ";
export const GET_SINGLE_ORDER_FAIL = "GET_SINGLE_ORDER_FAIL ";
export const GET_SINGLE_ORDER_RESET = "GET_SINGLE_ORDER_RESET ";

export const ORDER_PAY = "ORDER_PAY";
export const ORDER_PAY_FAIL = "ORDER_PAY_FAIL";
export const ORDER_PAY_RESET = "ORDER_PAY_RESET";
