export const FETCH_PRODUCT_iNIT = " FETCH_PRODUCT_iNIT";
export const FETCH_PRODUCT_SUCCESS = " FETCH_PRODUCT_SUCCESS";
export const FETCH_PRODUCT_FAIL = " FETCH_PRODUCT_FAIL";

export const FETCH_SINGLE_PRODUCT_iNIT = " FETCH_SINGLE_PRODUCT_iNIT";
export const FETCH_SINGLE_PRODUCT_SUCCESS = " FETCH_SINGLE_PRODUCT_SUCCESS";
export const FETCH_SINGLE_PRODUCT_FAIL = " FETCH_SINGLE_PRODUCT_FAIL";

export const FETCH_DISCOUNT_PRODUCT_iNIT = " FETCH_DISCOUNT_PRODUCT_iNIT";
export const FETCH_DISCOUNT_PRODUCT_SUCCESS = " FETCH_DISCOUNT_PRODUCT_SUCCESS";
export const FETCH_DISCOUNT_PRODUCT_FAIL = " FETCH_DISCOUNT_PRODUCT_FAIL";
