export const ADD_WISH_LIST_INIT = "ADD_WISH_LIST_INIT ";
export const ADD_WISH_LIST_SUCC = "ADD_WISH_LIST_SUCC ";
export const ADD_WISH_LIST_FAIL = "ADD_WISH_LIST_FAIL ";
export const WISH_LIST_RESET = " WISH_LIST_RESET";

export const GET_WISH_LIST_INIT = "GET_WISH_LIST_INIT ";
export const GET_WISH_LIST_SUCC = "GET_WISH_LIST_SUCC ";
export const GET_WISH_LIST_FAIL = "GET_WISH_LIST_FAIL ";

export const DEL_WISH_LIST_INIT = "DEL_WISH_LIST_INIT ";
export const DEL_WISH_LIST_SUCC = "DEL_WISH_LIST_SUCC ";
export const DEL_WISH_LIST_FAIL = "DEL_WISH_LIST_FAIL ";
export const DEL_WISH_LIST_RESET = " DEL_WISH_LIST_RESET";
