export const GET_ORDERS_INIT = "GET_ORDERS_INIT";
export const GET_ORDERS_SUCC = "GET_ORDERS_SUCC";
export const GET_ORDERS_FAIL = "GET_ORDERS_FAIL";

export const ORDER_DELIVERED_INIT = "ORDER_DELIVERED_INIT";
export const ORDER_DELIVERED_SUCC = "ORDER_DELIVERED_SUCC";
export const ORDER_DELIVERED_FAIL = "ORDER_DELIVERED_FAIL";
export const ORDER_DELIVERED_RESET = "ORDER_DELIVERED_RESET";
