export const GET_PRODUCTS_INIT = " GET_PRODUCTS_INIT ";
export const GET_PRODUCTS_SUCC = " GET_PRODUCTS_SUCC ";
export const GET_PRODUCTS_FAIL = " GET_PRODUCTS_FAIL ";

export const DELETE_PRODUCT = "DELETE_PRODUCT";
export const DELETE_PRODUCT_INIT = "DELETE_PRODUCT_INIT";
export const DELETE_PRODUCT_FAIL = "DELETE_PRODUCT_FAIL";

export const CREATE_PRODUCTS_INIT = " CREATE_PRODUCTS_INIT ";
export const CREATE_PRODUCTS_SUCC = " CREATE_PRODUCTS_SUCC ";
export const CREATE_PRODUCTS_FAIL = " CREATE_PRODUCTS_FAIL ";
export const CREATE_PRODUCTS_RESET = " CREATE_PRODUCTS_RESET ";
